---

- hosts: all
  gather_facts: false
  remote_user: root
  tasks:
#    - name: Update
#      apt:
#        name: "*"
#        state: latest

    - name: Ensure python is available
      apt:
        name: python-minimal
        allow_unauthenticated: yes

    - name: Ensure python-apt is available
      apt:
        name: python-apt
        allow_unauthenticated: yes

    - name: Ensure python-apt is available
      apt:
        name: sudo
        allow_unauthenticated: yes

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

- hosts: debrepo

  roles:
    - role: setup-users
      users: [ "reprepro" ]

    - role: gpg_key
      gpg_key_user: "reprepro"

#    - role: generate_gpgkey
#      gpg_generator_user: 'reprepro'
#      gpg_user: 'reprepro'
#      gpg_realname: 'reprepro'
#      gpg_useremail: 'reprepro@localhost'
#      gpg_pubkeyfile: 'debrepo.pub'
#      gpg_privkeyfile: 'debrepo.priv'

  tasks:
    - name: Export PGP key
      become: yes
      become_user: reprepro
      raw: gpg --armor --export reprepro@localhost --output $HOME/reprepro@localhost.gpg.key


    - name: Install Apache web server
      apt:
        name: apache2
        state: latest

#    - name: Copy Apache configuration
#      template: src=debrepo.conf.j2 dest=/etc/apache2/sites-available/debrepo.conf mode=775 owner=www-data group=www-data

#    - name: Link website in Apache
#      file:
#        src: /etc/apache2/sites-available/debrepo.conf
#        dest: /etc/apache2/sites-enabled/debrepo.conf
#        owner: www-data
#        group: www-data
#        state: link

    - name: Create incoming directories
      file: path=/var/www/{{item}} state=directory mode=775 owner=www-data group=www-data
      with_items:
        - dev
        - staging
        - prod
        - bin

    - name: Copy cron job
      template: src=cronjob.sh.j2 dest=/var/www/bin/cronjob.sh mode=775 owner=www-data group=www-data

    - name: Install reprepro
      apt:
        name: reprepro
        state: latest

    - name: Install cron job
      become: yes
      become_user: reprepro
      cron:
        name: "Update Debian Repository"
        minute: "*/10"
        job: "/var/www/bin/cronjob.sh"
